#!/usr/bin/env bash

# https://stackoverflow.com/a/2990533
echoerr() {
    printf "%s\n" "$*" >&2;
}

ME=$(basename ${BASH_SOURCE[0]})

if ! command -v fzf &> /dev/null
then
    echo 'fzf' could not be found. Install before retrying.
    exit 1
fi

# Get profile
#PROFILE=$(aws configure list-profiles | fzf)
PROFILE=$(grep -oP "^\[profile ([a-zA-Z0-9\-]+)" ~/.aws/config | sed "s/\[profile //g" | fzf)

if [[ ! -z ${BASH_VERSION} ]]; then
    # User is using Bash
    [[ "${BASH_SOURCE[0]}" != "${0}" ]] && IS_SOURCED=true

    if [[ $IS_SOURCED = "true" ]]; then
        # Using is running this command with the source prefix '.' or 'source'
        export AWS_PROFILE="$PROFILE"
    else
        echo "To use AWS environment, run:"
        echo "aws configure sso (one time), then aws sso login"
        echo "export AWS_PROFILE=$PROFILE"
        echo
        echo "Hint: To set this automatically, use"
        echo ". $ME $@"
    fi
else
    echo "Terminal is not supported, so you will have to set this environment variable manually:"
    echo AWS_PROFILE="$PROFILE"
fi

# Log in
if [[ "$*" == *"-l"* ]]; then
    aws sso login
fi
